#ifndef DEFINES_H
#define DEFINES_H

typedef enum {
    ASN_TAG_TYPE_INTEGER           = 0x02,
    ASN_TAG_TYPE_BIT_STRING        = 0x03,
    ASN_TAG_TYPE_OCTET_STRING      = 0x04,
    ASN_TAG_TYPE_OBJECT_IDENTIFIER = 0x06,
    ASN_RAW_TYPE_SEQUENCE          = 0x30,
    ASN_RAW_TYPE_EXPLICIT          = 0xA0,
} TAG_TYPE;

/* TLV */
#define TAG_DATA_OBJECT_FIRST_BYTE 0x20
#define TAG_NUMBER_FIRST_BYTE      0x1F

#define LENGTH_SECOND_BYTE         0x7F
#define LEGNTH_SECOND_BYTE_ONE     0x81
#define LEGNTH_SECOND_BYTE_TWO     0x82

#define ELLIPTIC_CURVE_POINT_ONLY1 0x02
#define ELLIPTIC_CURVE_POINT_ONLY2 0x03
#define ELLIPTIC_CURVE_POINT_BOTH  0x04

#define KEY_TYPE_EC_PUBKEY         0xF0000001
#define KEY_TYPE_EC_PRIKEY         0xF0000002

#define KEY_TYPE_RSA_PUBKEY        0xF0000003
#define KEY_TYPE_RSA_PRIKEY        0xF0000004

#define KEY_TYPE_DSA_PUBKEY        0xF0000005
#define KEY_TYPE_DSA_PRIKEY        0xF0000006

#endif